### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by ebisbe** [omatech/mage#24]
Teniu una regressio a https://github.com/omatech/mage/compare/v0.4.3-alpha...v0.4.4-alpha Fitxers

- [x]  src/app/Notifications/MailResetPasswordNotification.php

- [x] src/app/Notifications/MailWelcomeNotification.php

- [x] src/app/Notifications/MailWelcomeWithoutPasswordNotification.php

**Comment by ghost** [comment]
@ebisbe merci!
